### PR TITLE
spelling errors

### PR DESCRIPTION
**Pull request by glael**

### CODE REVIEW

**Comment by stanriders** [comment]
ugh, could you please keep your commits in ONE branch?

**Comment by glael** [comment]
sorry. just editing things i see while playing.

**Comment by stanriders** [comment]
fyi, you can add commits to one branch even after making pullreq. Please make further changes only in this branch to keep things less chaotic

**Comment by glael** [comment]
will do

**Comment by stanriders** [comment]
thanks

**Comment by glael** [comment]
fixed it (ill be continuing tomorrow (there are probably more errors to be found)

**Comment by stanriders** [comment]
good! tell me when you finish and i'll merge your fixes

**Comment by glael** [comment]
Suzu route done, Hisao next

**Comment by glael** [comment]
finished. That should be all language errors (unless i missed any).

**Comment by stanriders** [comment]
Good job! Merging

**Pull request merged**
